name: CI
on: push

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').dependencies['@playwright/test'].version)")" >> $GITHUB_ENV

      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Authentification Google Cloud
            uses: google-github-actions/auth@v1
            with:
              credentials_json: ${{ secrets.GCP_SA_KEY }}
          - name: Build and push Docker image
            run: |
              gcloud builds submit --tag gcr.io/methodo-app-lucas/react-app
          - name: Deploy to Google Cloud Run
            run: |
              gcloud run deploy methodo-app-lucas \
                --image gcr.io/methodo-app-lucas/react-app \
                --platform managed \
                --allow-unauthenticated \
                --port 80 \
                --region europe-west1 \





